services:
    ollama:
        build: .
        container_name: ollama
        networks:
            - ollama-net
        volumes:
            - ollama:/root/.ollama

    api:
        build: ./backend/.
        container_name: fastapi
        networks:
            - ollama-net
        depends_on:
            - ollama

        develop:
            watch:
                - action: sync
                  path: ./backend
                  target: /app
                - action: rebuild
                  path: ./backend/Dockerfile

    web:
        build: ./frontend/.
        container_name: webui
        networks:
            - ollama-net
        depends_on:
            - api
        ports:
            - "80:80"
        develop:
            watch:
                - action: sync
                  path: ./frontend
                  target: /usr/share/nginx/html
                - action: rebuild
                  path: ./frontend/Dockerfile

networks:
    ollama-net:
        driver: bridge
volumes:
    ollama:
