version: '3.8'

services:
  ollama:
    build: .
    container_name: ollama
    networks:
      - ollama-net
    volumes:
      - ollama:/root/.ollama

  api:
    build: ./backend/.
    container_name: fastapi
    networks:
      - ollama-net
    depends_on:
      - ollama

  web:
    build: ./frontend/.
    container_name: webui
    networks:
      - ollama-net
    depends_on:
      - api
    ports:
      - "80:80"

networks:
  ollama-net:
    driver: bridge
volumes:
  ollama:
